[general]
enable_bucket = true
caption_extension = '.txt'

[[datasets]]
resolution = 512
batch_size = 2

  [[datasets.subsets]]
  image_dir = '/data/sd_dataset/shark_png'
  num_repeats = 1
  
  [[datasets.subsets]]
  image_dir = '/data/sd-dataset/shark_prior'
  num_repeats = 1
  is_reg = true